<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests\Unit;

use Brain\Monkey\Functions;
use \StudioPress\Genesis\Upgrade\Upgrade_DB_101 as Upgrader;

/**
 * Test Upgrade_DB_101.
 */
class Upgrade_DB_101_Test extends TestCase {

	/**
	 * Test upgrade method.
	 */
	public function test_upgrade() {
		Functions\expect( 'genesis_update_settings' )
			->once()
			->with(
				[
					'nav_home'         => 1,
					'nav_twitter_text' => 'Follow me on Twitter',
					'subnav_home'      => 1,
				]
			);

		( new Upgrader() )->upgrade();
	}

}
