<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests\Unit;

use Brain\Monkey\Functions;
use \StudioPress\Genesis\Upgrade\Upgrade_DB_3000 as Upgrader;

/**
 * Test Upgrade_DB_3000.
 */
class Upgrade_DB_3000_Test extends TestCase {
	/**
	 * Test upgrade method.
	 */
	public function test_upgrade() {
		Functions\expect( 'genesis_get_option' )
			->once()
			->with( 'header_scripts' )
			->andReturn( 'some header scripts' );

		Functions\expect( 'genesis_get_option' )
			->twice()
			->with( 'adsense_id' )
			->andReturn( '1234' );

			// phpcs:disable -- Script is added to header scripts directly. No enqueue required.
			$adsense = <<<ADSENSE
<script async src="http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
(adsbygoogle = window.adsbygoogle || []).push({
google_ad_client: "1234",
enable_page_level_ads: true,
tag_partner: "genesis"
});
</script>
ADSENSE;

		Functions\expect( 'genesis_update_settings' )
			->once()
			->with(
				[
					'header_scripts' => 'some header scripts' . "\n" . $adsense,
				]
			);

		( new Upgrader() )->upgrade();
	}

}
