<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests\Unit;

use Brain\Monkey\Functions;
use \StudioPress\Genesis\Upgrade\Upgrade_DB_1700 as Upgrader;

/**
 * Test Upgrade_DB_1700.
 */
class Upgrade_DB_1700_Test extends TestCase {
	/**
	 * Test upgrade method.
	 */
	public function test_upgrade() {
		global $wpdb;
		$real_wpdb = $wpdb;

		//phpcs:ignore WordPress.WP.GlobalVariablesOverride.Prohibited -- Mocking $wpdb.
		$wpdb = \Mockery::mock( 'wpdb' );
		$wpdb->shouldReceive( 'query' )->twice()->andReturnUsing(
			static function( $query ) {
				return $query;
			}
		);
		$wpdb->usermeta = 'wp_usermeta';

		$wpdb->shouldReceive( 'prepare' )
			->once()
			->with(
				"DELETE FROM $wpdb->usermeta WHERE meta_key = %s OR meta_key = %s",
				'meta-box-order_toplevel_page_genesis',
				'meta-box-order_genesis_page_seosettings'
			)
			->andReturnUsing(
				static function ( $query ) {
						return $query;
				}
			);

		$wpdb->shouldReceive( 'prepare' )
			->once()
			->with(
				"UPDATE $wpdb->usermeta SET meta_value = %s WHERE meta_key = %s OR meta_key = %s",
				'1',
				'screen_layout_toplevel_page_genesis',
				'screen_layout_genesis_page_seosettings'
			)
			->andReturnUsing(
				static function ( $query ) {
						return $query;
				}
			);

		( new Upgrader() )->upgrade();

		//phpcs:ignore WordPress.WP.GlobalVariablesOverride.Prohibited -- Restore $wpdb.
		$wpdb = $real_wpdb;
	}
}
