<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests\Unit;

use Brain\Monkey\Functions;
use \StudioPress\Genesis\Upgrade\Upgrade_DB_2209 as Upgrader;

/**
 * Test Upgrade_DB_2209.
 */
class Upgrade_DB_2209_Test extends TestCase {
	/**
	 * Test migration from options table to proper term meta.
	 */
	public function test_add_term_meta() {
		$sample_term_meta = [
			1 => [
				'headline'   => 'Sample Term 1',
				'intro_text' => 'Sample Term 1 description',
			],
			2 => [
				'headline'   => 'Sample Term 2',
				'intro_text' => 'Sample Term 2 description',
			],
		];

		Functions\when( 'get_option' )->justReturn( $sample_term_meta );

		Functions\expect( 'add_term_meta' )
			->once()
			->with(
				1,
				'headline',
				'Sample Term 1',
				true
			);

		Functions\expect( 'add_term_meta' )
			->once()
			->with(
				1,
				'intro_text',
				'Sample Term 1 description',
				true
			);

		Functions\expect( 'add_term_meta' )
			->once()
			->with(
				2,
				'headline',
				'Sample Term 2',
				true
			);

		Functions\expect( 'add_term_meta' )
			->once()
			->with(
				2,
				'intro_text',
				'Sample Term 2 description',
				true
			);

		( new Upgrader() )->upgrade();
	}
}
