<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis\Tests\System
 * @author  XWP, Google, StudioPress, and contributors
 * @license GPL-2.0-or-later
 * @link    https://github.com/studiopress/genesis-amp
 */

namespace StudioPress\Genesis\Tests\System;

use AMP_DOM_Utils;
use Genesis_AMP_Menu_Combiner;

/**
 * Test Genesis Responsive Menu Handler.
 *
 * @group amp
 */
class Genesis_AMP_Menu_Combiner_Test extends TestCase {

	/**
	 * Menu configuration.
	 *
	 * @var array
	 */
	protected $config;

	/**
	 * Prepares the test environment before each test.
	 */
	public function setUp() {
		parent::setUp();

		require_once GENESIS_THEME_DIR . '/../../plugins/amp/amp.php';
		require_once GENESIS_THEME_DIR . '/lib/classes/class-genesis-amp-menu-combiner.php';
	}

	/**
	 * Data for the tests.
	 *
	 * @return array test data.
	 */
	public function get_data() {
		return [
			'primary_as_main_menu'               => [
				[ '.nav-primary', '.nav-off-screen' ],
				$this->get_nav_off_screen() . $this->get_nav_primary(),
				$this->get_nav_off_screen() . $this->get_primary_as_main_menu(),
			],
			'primary_as_main_menu-rev-source'    => [
				[ '.nav-primary', '.nav-off-screen' ],
				$this->get_nav_primary() . $this->get_nav_off_screen(),
				$this->get_primary_as_main_menu() . $this->get_nav_off_screen(),
			],
			'off_screen_as_main_menu'            => [
				[ '.nav-off-screen', '.nav-primary' ],
				$this->get_nav_off_screen() . $this->get_nav_primary(),
				$this->get_off_screen_as_main_menu() . $this->get_nav_primary(),
			],
			'off_screen_as_main_menu-rev-source' => [
				[ '.nav-off-screen', '.nav-primary' ],
				$this->get_nav_primary() . $this->get_nav_off_screen(),
				$this->get_nav_primary() . $this->get_off_screen_as_main_menu(),
			],
		];
	}


	/**
	 * Test the combiner.
	 *
	 * @dataProvider get_data
	 *
	 * @param array  $menus_to_combine Menus to combine.
	 * @param string $source           Source.
	 * @param string $expected         Expected.
	 */
	public function test_combiner( $menus_to_combine, $source, $expected ) {

		if ( ! function_exists( 'amp_init' ) ) {
			$this->markTestSkipped( 'Please install the AMP for WordPress plugin: https://github.com/Automattic/amp-wp' );
		}

		$dom      = AMP_DOM_Utils::get_dom_from_content( $source );
		$combiner = new Genesis_AMP_Menu_Combiner( $dom, [ 'combine' => $menus_to_combine ] );
		$combiner->sanitize();

		$content = AMP_DOM_Utils::get_content_from_dom( $dom );
		$this->assertEquals( $this->minify_html( $expected ), $this->minify_html( $content ) );
	}


	/**
	 * Returns the nav-off-screen HTML.
	 *
	 * @return string
	 */
	private function get_nav_off_screen() {
		$html = <<<HTML
<nav class="nav-off-screen genesis-responsive-menu" itemscope itemtype="https://schema.org/SiteNavigationElement">
	<ul id="menu-nav-off-screen" class="menu genesis-nav-menu">
		<li id="menu-item-54" class="menu-item menu-item-54">
			<a href="#" itemprop="url"><span itemprop="name">Offscreen 1</span></a></li>
		<li id="menu-item-57" class="menu-item menu-item-57">
			<a href="#" itemprop="url"><span itemprop="name">Offscreen 2</span></a></li>
		<li id="menu-item-58" class="menu-item menu-item-58">
			<a href="#" itemprop="url"><span itemprop="name">Offscreen 3</span></a>
		</li>
	</ul>
</nav>
HTML;

		return $html;
	}

	/**
	 * Returns the nav-primary HTML.
	 *
	 * @return string
	 */
	private function get_nav_primary() {
		$html = <<<HTML
<nav id="genesis-nav-primary" class="nav-primary genesis-responsive-menu" aria-label="Main" itemscope itemtype="https://schema.org/SiteNavigationElement">
	<div class="wrap">
		<ul id="menu-main" class="menu genesis-nav-menu menu-primary">
			<li id="menu-item-8" class="menu-item menu-item-8">
				<a href="#" itemprop="url"><span itemprop="name">Primary 1</span></a>
			</li>
			<li id="menu-item-6" class="menu-item menu-item-6">
				<a href="#" itemprop="url"><span itemprop="name">Primary 2</span></a>
			</li>
		</ul>
	</div>
</nav>
HTML;

		return $html;
	}

	/**
	 * Returns the off-screen navigation menu combined with the primary navigation menu.
	 *
	 * @return string
	 */
	private function get_primary_as_main_menu() {
		$html = <<<HTML
<nav id="genesis-nav-primary" class="nav-primary genesis-responsive-menu" aria-label="Main" itemscope itemtype="https://schema.org/SiteNavigationElement">
	<div class="wrap">
		<ul id="menu-main" class="menu genesis-nav-menu menu-primary">
			<li id="menu-item-8" class="menu-item menu-item-8">
				<a href="#" itemprop="url"><span itemprop="name">Primary 1</span></a>
			</li>
			<li id="menu-item-6" class="menu-item menu-item-6">
				<a href="#" itemprop="url"><span itemprop="name">Primary 2</span></a>
			</li>
			<li id="menu-item-54" class="genesis-amp-combined menu-item menu-item-54">
				<a href="#" itemprop="url"><span itemprop="name">Offscreen 1</span></a></li>
			<li id="menu-item-57" class="genesis-amp-combined menu-item menu-item-57">
				<a href="#" itemprop="url"><span itemprop="name">Offscreen 2</span></a></li>
			<li id="menu-item-58" class="genesis-amp-combined menu-item menu-item-58">
				<a href="#" itemprop="url"><span itemprop="name">Offscreen 3</span></a>
			</li>
		</ul>
	</div>
</nav>
HTML;

		return $html;
	}

	/**
	 * Returns the primary navigation menu combined with the off-screen navigation menu.
	 *
	 * @return string
	 */
	private function get_off_screen_as_main_menu() {
		$html = <<<HTML
<nav class="nav-off-screen genesis-responsive-menu" itemscope itemtype="https://schema.org/SiteNavigationElement">
	<ul id="menu-nav-off-screen" class="menu genesis-nav-menu">
		<li id="menu-item-54" class="menu-item menu-item-54">
			<a href="#" itemprop="url"><span itemprop="name">Offscreen 1</span></a></li>
		<li id="menu-item-57" class="menu-item menu-item-57">
			<a href="#" itemprop="url"><span itemprop="name">Offscreen 2</span></a></li>
		<li id="menu-item-58" class="menu-item menu-item-58">
			<a href="#" itemprop="url"><span itemprop="name">Offscreen 3</span></a>
		</li>
		<li id="menu-item-8" class="genesis-amp-combined menu-item menu-item-8">
			<a href="#" itemprop="url"><span itemprop="name">Primary 1</span></a>
		</li>
		<li id="menu-item-6" class="genesis-amp-combined menu-item menu-item-6">
			<a href="#" itemprop="url"><span itemprop="name">Primary 2</span></a>
		</li>
	</ul>
</nav>
HTML;

		return $html;
	}

}
