<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Tests
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests\System;

/**
 * Test post type support
 *
 * @group post-type-support
 */
class Post_Type_Support_Test extends TestCase {
	/**
	 * Tests default post type supports common to pages and posts.
	 *
	 * @param string $post_type The post type to test.
	 */
	protected function common_supports( $post_type ) {
		foreach ( [ 'genesis-seo', 'genesis-scripts', 'genesis-layouts', 'genesis-breadcrumbs-toggle' ] as $feature ) {
			$this->assertTrue( post_type_supports( $post_type, $feature ), "The '$post_type' post type should support the '$feature' feature, but it doesn't!" );
		}
	}

	/**
	 * Tests default post type supports unique to pages.
	 */
	protected function page_supports() {
		foreach ( [ 'genesis-title-toggle' ] as $feature ) {
			$this->assertTrue( post_type_supports( 'page', $feature ), "The 'page' post type should support the '$feature' feature, but it doesn't!" );
		}
	}

	/**
	 * Tests `genesis_theme_support()` and post type support.
	 *
	 * @covers genesis_theme_support
	 */
	public function test_support() {
		$this->assertTrue( function_exists( 'genesis_theme_support' ), 'genesis_theme_support() is not defined!' );

		// Tests supports shared by both types.
		$types = [ 'post', 'page' ];
		array_walk( $types, [ $this, 'common_supports' ] );

		// Tests unique supports.
		$this->page_supports();
	}
}
