<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Tests
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests\Unit;

use Brain\Monkey\Functions;
use StudioPress\Genesis\Tests\Genesis_Unit_Test_Dummy_1;
use StudioPress\Genesis\Tests\Genesis_Unit_Test_Dummy_2;

/**
 * Test general functions.
 *
 * @group functions
 */
class General extends TestCase {
	/**
	 * Test Genesis can detect plugins via class, constants and functions.
	 */
	public function test_genesis_detect_plugin() {
		require GENESIS_THEME_DIR . '/tests/fixtures/dummies.php';

		// Separate these out so each can be tested independently.
		$things_to_test = [
			'class'    => [
				'classes' => [ Genesis_Unit_Test_Dummy_1::class, Genesis_Unit_Test_Dummy_2::class ],
			],
			'constant' => [
				'constants' => [ 'GENESIS_UNIT_TEST_DUMMY_1', 'GENESIS_UNIT_TEST_DUMMY_2' ],
			],
			'function' => [
				'functions' => [ 'StudioPress\Genesis\Tests\genesis_unit_test_dummy_1', 'StudioPress\Genesis\Tests\genesis_unit_test_dummy_2' ],
			],
		];

		foreach ( $things_to_test as $type => $tests ) {
			self::assertTrue( genesis_detect_plugin( $tests ), 'genesis_detect_plugin() failed to detect a ' . $type );
		}
	}

	/**
	 * Tests genesis_get_config().
	 */
	public function test_genesis_get_config() {
		Functions\when( 'get_template_directory' )->justReturn( GENESIS_THEME_DIR . '/tests/fixtures/test-configs/parent' );
		Functions\when( 'get_stylesheet_directory' )->justReturn( GENESIS_THEME_DIR . '/tests/fixtures/test-configs/child' );

		self::assertEquals(
			genesis_get_config( 'plugins' ),
			[
				'genesis-simple-sidebars' => false,
				'genesis-simple-hooks'    => false,
				'akismet'                 => true,
				'jetpack'                 => true,
			]
		);

		self::assertEquals(
			genesis_get_config( 'themes' ),
			[
				'authority-pro'  => true,
				'essence-pro'    => true,
				'genesis-sample' => true,
			]
		);

		self::assertEquals(
			genesis_get_config( 'settings' ),
			[
				'foo' => 'bar',
				'abc' => '123',
			]
		);

	}
}
