<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests\Unit;

use Brain\Monkey\Functions;
use Mockery;

/**
 * Test version functions.
 *
 * @group upgrade
 */
class Version extends TestCase {
	/**
	 * Test that Genesis first version function uses stored version.
	 */
	public function test_genesis_first_version_uses_stored_version() {
		Functions\when( 'genesis_get_option' )->justReturn( '9.9.9' );

		self::assertSame( '9.9.9', \genesis_first_version() );
	}

	/**
	 * Test that Genesis first version function ignores stored version if it doesn't exist.
	 */
	public function test_genesis_first_version_is_not_stored() {
		Functions\when( 'genesis_get_option' )->justReturn( '' );

		self::assertSame( PARENT_THEME_VERSION, \genesis_first_version() );
	}

	/**
	 * Test `genesis_get_expiring_setting`.
	 *
	 * @covers ::genesis_get_db_version
	 *
	 * @dataProvider data_genesis_get_db_version
	 *
	 * @param string $db_version    The database version.
	 * @param string $theme_version The theme version.
	 * @param mixed  $expected      The expected result.
	 */
	public function test_genesis_get_db_version( $db_version, $theme_version, $expected ) {
		Functions\expect( 'genesis_get_option' )
			->atLeast()
			->once()
			->andReturn( $db_version, $theme_version );

		$result = genesis_get_db_version();

		self::assertEquals( $expected, $result );
	}

	/**
	 * Data provider for testing genesis_get_db_version().
	 *
	 * @return array
	 */
	public function data_genesis_get_db_version() {
		return [
			'db_version exists' => [
				'1111',
				'2.2.2',
				'1111',
			],
			'db_version does not exist, theme_version exists' => [
				'',
				'3.3.3',
				'333',
			],
			'db_version does not exist, theme_version exists but is not long enough' => [
				'',
				'4.4',
				'440',
			],
			'db_version does not exist, theme_version does not exist' => [
				'',
				'',
				'9998',
			],
		];
	}
}
