<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Tests
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests\System;

/**
 * Test SEO functions.
 *
 * @group functions
 */
class Seo_Test extends TestCase {

	/**
	 * The ID of the created page.
	 *
	 * @var int
	 */
	protected $page_id;

	/**
	 * Sets the Primary Title H1 Genesis SEO setting to the given value.
	 *
	 * @param string $value The H1 setting: 'title', 'description' or 'neither'.
	 */
	protected function set_primary_title_h1( $value ) {
		$seo_options               = get_option( GENESIS_SEO_SETTINGS_FIELD );
		$seo_options['home_h1_on'] = $value;
		update_option( GENESIS_SEO_SETTINGS_FIELD, $seo_options );
	}

	/**
	 * Prepares the test environment before each test.
	 */
	public function setUp() {
		parent::setUp();

		// Insert a post with a heading level 1 block.
		$this->page_id = wp_insert_post(
			[
				'post_title'   => 'homepage',
				'post_content' => '<!-- wp:heading {"level":1} --><h1>Heading Level 1</h1><!-- /wp:heading -->',
				'post_status'  => 'publish',
				'post_type'    => 'page',
			]
		);

		// Use the page as the static homepage.
		update_option( 'page_on_front', $this->page_id );
		update_option( 'show_on_front', 'page' );

		$this->set_primary_title_h1( 'title' );
	}

	/**
	 * Test `genesis_maybe_clear_primary_title_h1()` sets `home_h1_on` setting
	 * to 'neither' if static homepage contains an h1 block.
	 */
	public function test_h1_none_if_static_homepage_contains_h1_block() {
		// Edit and update the post. This should trigger `genesis_maybe_clear_primary_title_h1()`
		// via the `save_post` action, which sets the Primary Title H1 to 'neither'.
		wp_update_post(
			[
				'ID'         => $this->page_id,
				'post_title' => 'Page title updated',
			]
		);

		self::assertEquals( 'neither', genesis_get_seo_option( 'home_h1_on', false ) );
	}

	/**
	 * Test `genesis_maybe_clear_primary_title_h1()` sets `home_h1_on` setting
	 * to 'neither' if static homepage contains a deeply nested h1 block.
	 */
	public function test_h1_none_if_static_homepage_contains_deep_h1_block() {
		// Edit and update the post. This should trigger `genesis_maybe_clear_primary_title_h1()`
		// via the `save_post` action, which sets the Primary Title H1 to 'neither'.
		wp_update_post(
			[
				'ID'           => $this->page_id,
				'post_content' => '<!-- wp:atomic-blocks/ab-container --><div class="wp-block-atomic-blocks-ab-container ab-block-container"><div class="ab-container-inside"><div class="ab-container-content" style="max-width:1600px"><!-- wp:atomic-blocks/ab-container --><div class="wp-block-atomic-blocks-ab-container ab-block-container"><div class="ab-container-inside"><div class="ab-container-content" style="max-width:1600px"><!-- wp:atomic-blocks/ab-container --><div class="wp-block-atomic-blocks-ab-container ab-block-container"><div class="ab-container-inside"><div class="ab-container-content" style="max-width:1600px"><!-- wp:atomic-blocks/ab-container --><div class="wp-block-atomic-blocks-ab-container ab-block-container"><div class="ab-container-inside"><div class="ab-container-content" style="max-width:1600px"><!-- wp:heading {"level":1} --><h1>Nested Heading Level 1</h1><!-- /wp:heading --></div></div></div><!-- /wp:atomic-blocks/ab-container --></div></div></div><!-- /wp:atomic-blocks/ab-container --></div></div></div><!-- /wp:atomic-blocks/ab-container --></div></div></div><!-- /wp:atomic-blocks/ab-container -->',
			]
		);

		self::assertEquals( 'neither', genesis_get_seo_option( 'home_h1_on', false ) );
	}

	/**
	 * Test `genesis_maybe_clear_primary_title_h1()` leaves `home_h1_on`
	 * unchanged if static homepage contains no h1 block.
	 */
	public function test_h1_unchanged_if_static_homepage_contains_no_h1_block() {
		// Show that it also works with description rather than title.
		$this->set_primary_title_h1( 'description' );

		// Edit and update the post. This should trigger `genesis_maybe_clear_primary_title_h1()`
		// via the `save_post` action, but not alter the Primary Title H1 setting as the page
		// contains no heading level 1 block.
		wp_update_post(
			[
				'ID'           => $this->page_id,
				'post_content' => '<!-- wp:heading --><h2>Heading Level 2</h2><!-- /wp:heading -->',
			]
		);

		self::assertEquals( 'description', genesis_get_seo_option( 'home_h1_on', false ) );
	}

	/**
	 * Test `genesis_maybe_clear_primary_title_h1()` leaves `home_h1_on`
	 * unchanged if the homepage is set to display latest posts, even if
	 * a static homepage was previously set and still contains an h1.
	 */
	public function test_h1_unchanged_if_latest_posts_shown_on_front() {
		// Set the homepage to latest posts, but leave the page_on_front stored.
		// This emulates having had a static homepage in the past and then
		// switching to Latest Posts for the homepage. It shows that the title
		// h1 is only changed if the current homepage still uses a static page.
		update_option( 'show_on_front', 'posts' );

		// Edit and update the post. This should trigger `genesis_maybe_clear_primary_title_h1()`
		// via the `save_post` action, but not alter the Primary Title H1 setting as the site
		// is not using a static homepage.
		wp_update_post(
			[
				'ID'         => $this->page_id,
				'post_title' => 'Page title updated',
			]
		);

		self::assertEquals( 'title', genesis_get_seo_option( 'home_h1_on', false ) );
	}

	/**
	 * Test `genesis_maybe_clear_primary_title_h1()` leaves `home_h1_on`
	 * unchanged if Genesis SEO is disabled.
	 */
	public function test_h1_unchanged_if_genesis_seo_disabled() {
		genesis_disable_seo();

		// Edit and update the post. This should trigger `genesis_maybe_clear_primary_title_h1()`
		// via the `save_post` action, but not alter the Primary Title H1 setting because Genesis
		// SEO has been disabled.
		wp_update_post(
			[
				'ID'           => $this->page_id,
				'post_content' => 'Page title updated',
			]
		);

		// Disabling Genesis SEO makes `genesis_get_seo_option()` return an
		// empty array unless that filter is removed first.
		remove_filter( 'pre_option_' . GENESIS_SEO_SETTINGS_FIELD, '__return_empty_array' );
		self::assertEquals( 'title', genesis_get_seo_option( 'home_h1_on', false ) );
	}

}
