<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Tests
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests\Unit;

use Brain\Monkey\Functions;
use Genesis_Contributor;

/**
 * Test Genesis Contributor class.
 *
 * @group contributors
 */
class Genesis_Contributor_Test extends TestCase {

	/**
	 * Sets up the fixture, for example, open a network connection.
	 *
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		Functions\when( '__' )->returnArg();
		Functions\when( 'get_template_directory' )->justReturn( GENESIS_THEME_DIR );

		parent::setUp();
	}

	/**
	 * Test simple getters from instantiated object work correctly.
	 */
	public function test_genesis_contributor_can_get_values() {
		$contributor = new Genesis_Contributor(
			'Nathan Rice',
			'https://twitter.com/nathanrice',
			'https://0.gravatar.com/avatar/fdbd4b13e3bcccb8b48cc18f846efb7f?s=120',
			'lead-developer'
		);

		self::assertEquals( 'Nathan Rice', $contributor->get_name() );
		self::assertEquals( 'https://twitter.com/nathanrice', $contributor->get_profile_url() );
		self::assertEquals( 'https://0.gravatar.com/avatar/fdbd4b13e3bcccb8b48cc18f846efb7f?s=120', $contributor->get_avatar_url() );
		self::assertEquals( 'lead-developer', $contributor->get_role() );
		self::assertEquals( 'Lead Developer', $contributor->get_named_role() );
	}

	/**
	 * Test handling of role works correctly.
	 */
	public function test_genesis_contributor_can_get_named_role_for_contributor() {
		$contributor = new Genesis_Contributor(
			'Nathan Rice',
			'https://twitter.com/nathanrice',
			'https://0.gravatar.com/avatar/fdbd4b13e3bcccb8b48cc18f846efb7f?s=120',
			'contributor'
		);

		self::assertEquals( 'Contributor', $contributor->get_named_role() );
	}

	/**
	 * Test that unknown role returns an empty named role string.
	 */
	public function test_genesis_contributor_returns_empty_named_role_string_for_unknown_role() {
		$contributor = new Genesis_Contributor(
			'Nathan Rice',
			'https://twitter.com/nathanrice',
			'https://0.gravatar.com/avatar/fdbd4b13e3bcccb8b48cc18f846efb7f?s=120',
			'an unknown role'
		);

		self::assertEquals( '', $contributor->get_named_role() );
	}
}
