<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis\Tests\Unit
 * @author  XWP, Google, StudioPress, and contributors
 * @license GPL-2.0-or-later
 * @link    https://github.com/studiopress/genesis-amp
 */

namespace StudioPress\Genesis\Tests\Unit;

use Brain\Monkey\Functions;
use Genesis_Menu;

/**
 * Test Genesis Menu.
 *
 * @group amp
 */
class Genesis_Menu_Test extends TestCase {

	/**
	 * Sets up the fixture, for example, open a network connection.
	 *
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		require_once GENESIS_THEME_DIR . '/lib/classes/class-genesis-menu.php';

		parent::setUp();
	}

	/**
	 * Test handler hooks the right events when non-AMP.
	 */
	public function test_add_hooks() {
		$menu = new Genesis_Menu( 'amp-foo', [] );
		$menu->add_hooks();

		self::assertEquals( 10, has_action( 'wp_enqueue_scripts', [ $menu, 'enqueue_scripts' ] ) );
	}

	/**
	 * Test scripts are enqueued.
	 */
	public function test_scripts_are_enqueued() {
		$config = [
			'mainMenu'         => 'Menu',
			'menuIconClass'    => 'dashicons-before dashicons-menu',
			'subMenu'          => 'Submenu',
			'subMenuIconClass' => 'dashicons-before dashicons-arrow-down-alt2',
			'menuClasses'      => [
				'combine' => [
					'.nav-primary',
				],
				'others'  => [],
			],
		];
		$menu   = new Genesis_Menu( 'amp-foo', $config );

		Functions\expect( 'wp_enqueue_script' )
			->once()
			->with(
				'amp-foo-responsive-menu',
				'https://example.com/wp-content/themes/genesis/js/menu/responsive-menus.min.js',
				[ 'jquery' ],
				Genesis_Menu::SCRIPT_VERSION,
				true
			)
			->andReturnNull();
		Functions\expect( 'wp_localize_script' )
			->once()
			->with(
				'amp-foo-responsive-menu',
				'genesis_responsive_menu',
				$config
			)
			->andReturnNull();

		self::assertNull( $menu->enqueue_scripts() );
	}
}
