<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests\Unit;

use Brain\Monkey\Functions;
use Genesis_Search_Form;

/**
 * Test Search Form class.
 */
class Genesis_Search_Form_Test extends TestCase {

	/**
	 * Expected form output.
	 *
	 * @var string
	 */
	protected $expected_output;

	/**
	 * Sets up the fixture, for example, open a network connection.
	 *
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		Functions\stubs( [ 'apply_filters', '__' ] );
		Functions\when( 'get_template_directory' )->justReturn( GENESIS_THEME_DIR );
		Functions\when( 'get_search_query' )->justReturn();
		Functions\when( 'genesis_markup' )->alias(
			static function( $args ) {
				$markup  = '';
				$markup .= isset( $args['open'] ) ? sprintf( $args['open'], '' ) : '';
				$markup .= isset( $args['content'] ) ? $args['content'] : '';
				$markup .= isset( $args['close'] ) ? sprintf( $args['close'], '' ) : '';

				if ( ! empty( $args['echo'] ) ) {
					// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
					echo $markup;
				}
				return $markup;
			}
		);

		$this->expected_output = '<form ><label >Search site</label><input ><input ></form>';

		parent::setUp();
	}

	/**
	 * Test the standard form output.
	 */
	public function test_get_form_output() {
		$form = new Genesis_Search_Form();

		self::assertEquals( $this->expected_output, $form->get_form() );
	}

	/**
	 * Test the form output when a different label string is passed.
	 */
	public function test_get_form_with_different_label() {
		$strings = [
			'label' => 'Lorem ipsum',
		];

		$form = new Genesis_Search_Form( $strings );

		self::assertEquals( '<form ><label >Lorem ipsum</label><input ><input ></form>', $form->get_form() );
	}

}
