<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis\Tests
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests\Unit;

use Brain\Monkey\Functions;

/**
 * Test general functions.
 *
 * @group functions
 */
class Init extends TestCase {
	/**
	 * Test autoloader correctly builds file paths.
	 *
	 * @dataProvider autoloader_classes_and_outputs
	 *
	 * @param string $class        Prefixed or namespaced class.
	 * @param string $file_or_null Relative file path, or null.
	 */
	public function test_genesis_autoload_register( $class, $file_or_null ) {
		Functions\when( 'get_template_directory' )->justReturn( '' );
		self::assertEquals( $file_or_null, genesis_autoload_register( $class ) );
	}

	/**
	 * Data Provider for testing Genesis autoloader with library of class names and expected output.
	 *
	 * @return array Class name library.
	 */
	public function autoloader_classes_and_outputs() {
		return [
			// Named dataset => [ Prefixed class, Expected file location ].
			'Not a Genesis class.'                        => [ 'Foo_Admin', null ],
			'Single word after prefix.'                   => [ 'Genesis_Admin', '/lib/classes/class-genesis-admin.php' ],
			'Multiple words after prefix.'                => [ 'Genesis_Admin_Basic', '/lib/classes/class-genesis-admin-basic.php' ],

			// Named dataset => [Namespaced class, Expected file location ].
			'Not the correct root namespace.'             => [ 'Genesis\Admin', null ],
			'Single level after known root namespace.'    => [ 'StudioPress\Genesis\Admin', '/lib/classes/class-admin.php' ],
			'Multiple levels after known root namespace.' => [ 'StudioPress\Genesis\Admin\Basic', '/lib/classes/class-admin-basic.php' ],
		];
	}
}
