<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis\Tests\System
 * @author  XWP, Google, StudioPress, and contributors
 * @license GPL-2.0-or-later
 * @link    https://github.com/studiopress/genesis-amp
 */

namespace StudioPress\Genesis\Tests\System;

use Brain\Monkey\Functions;
use StudioPress\Genesis\Upgrade\Upgrade_DB_101 as Upgrader;

/**
 * Test Upgrade_DB_101.
 */
class Upgrade_DB_101_Test extends TestCase {
	/**
	 * Test that the upgrade updates the settings.
	 */
	public function test_upgrade_updates_settings() {
		update_option( GENESIS_SETTINGS_FIELD, [] );

		( new Upgrader() )->upgrade();

		$this->assertEquals( 1, genesis_get_option( 'nav_home', null, false ) );
		$this->assertEquals( 'Follow me on Twitter', genesis_get_option( 'nav_twitter_text', null, false ) );
		$this->assertEquals( 1, genesis_get_option( 'subnav_home', null, false ) );
	}
}
