<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

/**
 * Array of versions to iterate over when a db upgrade is necessary.
 *
 * Each number represents an upgrade class that will execute to handle db upgrades for that db version.
 *
 * Genesis will determine which number to start with based on the current `db_version` setting value.
 *
 * @since 3.1.0
 */
return [
	'101',
	'110',
	'112',
	'120',
	'130',
	'160',
	'1700',
	'1800',
	'1901',
	'2001',
	'2003',
	'2100',
	'2201',
	'2207',
	'2209',
	'2501',
	'2603',
	'2700',
	'3000',
	'3001',
	'3100',
	'3101',
];
