<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package StudioPress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests\Unit;

use Brain\Monkey\Filters;
use Brain\Monkey\Functions;
use Mockery;

/**
 * Test Genesis Onboarding functions.
 *
 * @group admin
 * @group onboarding
 * @group theme-activation
 */
class Genesis_Theme_Activation_Test extends TestCase {

	/**
	 * Test that genesis_import_child_theme_settings() properly handles configs of various types.
	 *
	 * @covers ::genesis_import_child_theme_settings
	 *
	 * @dataProvider data_genesis_import_child_theme_settings
	 *
	 * @param array $config   The configuration array.
	 * @param bool  $expected The expected output.
	 */
	public function test_genesis_import_child_theme_settings( $config, $expected ) {
		Functions\when( 'genesis_get_config' )->justReturn( $config );
		Functions\when( 'genesis_update_settings' )->justReturn( true );
		Functions\when( 'update_option' )->justReturn( true );

		$actual = genesis_import_child_theme_settings();

		self::assertEquals( $expected, $actual );
	}

	/**
	 * Data Provider for testing genesis_import_child_theme_settings().
	 *
	 * @return array
	 */
	public function data_genesis_import_child_theme_settings() {
		return [
			'correctly formatted config'   => [
				[
					'senses'        => [ // this is the setting key.
						'eyes'   => 'see',
						'ears'   => 'hear',
						'tongue' => 'taste',
						'nose'   => 'smell',
						'skin'   => 'touch',
					],
					'show_on_front' => 'page', // option with string value.
				],
				true,
			],
			'incorrectly formatted config' => [
				[
					'see',
					'hear',
					'taste',
					'smell',
					'touch',
					'show_on_front' => 'page',
				],
				false,
			],
			'empty config'                 => [
				[],
				false,
			],
		];
	}

}
