<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Tests
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests\System;

use Brain\Monkey\Functions;

/**
 * Test [footer_backtotop] deprecated shortcode.
 *
 * @group shortcodes
 */
class Footer_Backtotop_Test extends TestCase {

	/**
	 * Test genesis_footer_backtotop_shortcode() will trigger a deprecation notice.
	 *
	 * @group deprecated
	 */
	public function test_footer_backtoptop_will_trigger_a_deprecated_notice() {
		Functions\expect( '_deprecated_function' )
			->with( 'genesis_footer_backtotop_shortcode', '3.0.0' )
			->once();

		$this->assertEquals( '', genesis_footer_backtotop_shortcode( [] ) );
	}

}
