<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Tests
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests;

require __DIR__ . '/dummy-class-1.php';
require __DIR__ . '/dummy-class-2.php';

// First dummy constant.
define( 'GENESIS_UNIT_TEST_DUMMY_1', true );

// Second dummy constant.
define( 'GENESIS_UNIT_TEST_DUMMY_2', true );

/**
 * First dummy function.
 */
function genesis_unit_test_dummy_1() {}

/**
 * Second dummy function.
 */
function genesis_unit_test_dummy_2() {}
