<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Tests
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests\System;

use Brain\Monkey;
use Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration;
use \StudioPress\Genesis\Tests\TestCaseTrait;
use WP_UnitTestCase;

/**
 * Abstract base class for all system test case implementations.
 */
abstract class TestCase extends WP_UnitTestCase {
	use MockeryPHPUnitIntegration;
	use TestCaseTrait;

	/**
	 * Prepares the test environment before each test.
	 *
	 * @since 1.0.0
	 *
	 * @return void
	 */
	public function setUp() {
		parent::setUp();
		Monkey\setUp();
	}

	/**
	 * Cleans up the test environment after each test.
	 *
	 * @since 1.0.0
	 *
	 * @return void
	 */
	public function tearDown() {
		Monkey\tearDown();
		parent::tearDown();
	}

	/**
	 * Set specific POST key with a value.
	 *
	 * @param string $key   Key to set.
	 * @param string $value Value to set for key.
	 */
	protected function set_post( $key, $value ) {
		$_POST[ $key ]    = addslashes( $value );
		$_REQUEST[ $key ] = addslashes( $value );
	}

	/**
	 * Unset specific POST key.
	 *
	 * @param string $key Key to unset.
	 */
	protected function unset_post( $key ) {
		unset( $_POST[ $key ], $_REQUEST[ $key ] ); // phpcs:ignore WordPress.Security.NonceVerification
	}

	/**
	 * Custom assert, that HTML string contains a specific class.
	 *
	 * @param string $class  Class to check for.
	 * @param string $string String to check.
	 */
	protected function assertContainsClass( $class, $string ) {
		$this->assertRegExp( '#class=([\'"])[^\\1]*' . $class . '[^\\1]*\\1#', $string );
	}

	/**
	 * Toggle HTML5 support, to check tests pass in both modes.
	 *
	 * @param callable $html_callback Callable for HTML5 test.
	 *
	 * @since 3.0.0 Removed $xhtml_callback parameter as xhtml support was removed.
	 */
	protected function html( callable $html_callback ) {
		add_theme_support( 'html5' );
		$html_callback();
	}
}
