<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Tests
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

namespace StudioPress\Genesis\Tests\System;

use Genesis_Admin_Settings;

/**
 * Test sitewide scripts are saved and preserved when retrieved.
 *
 * @group settings
 * @group admin
 */
class Sitewide_Scripts_Test extends TestCase {

	/**
	 * Sample user script containing regular expressions.
	 *
	 * @var string
	 */
	protected $script = <<<'SCRIPT'
<script>
var re = /\w+/;
var re = new RegExp('\\w+');
</script>
SCRIPT;

	/**
	 * Sample CSS styles containing single quotes, double quotes, and backslashes.
	 *
	 * @var string
	 */
	protected $styles = <<<'STYLES'
<style>
p {
	font-family: 'Genesis Rocks', sans-serif;
}

*::after {
  content: "\47\45\4E\45\53\49\53\20\52\4F\43\4B\53\21";
}
</style>
STYLES;

	/**
	 * Sample meta tags typically found in sitewide header scripts.
	 *
	 * @var string
	 */
	protected $meta = <<<'META'
<meta name="google-site-verification" content="abc123" />
<meta name='google-site-verification' content='abc123' />
<meta name=google-site-verification content=abc123 />
META;

	// phpcs:disable WordPress.WP.EnqueuedResources
	/**
	 * Sample user script element unslashed.
	 *
	 * @var string
	 */
	protected $script_element_unslashed = <<<'SCRIPT'
<script src="https://example.com"></script>
SCRIPT;

	/**
	 * Sample user script element slashed.
	 *
	 * @var string
	 */
	protected $script_element_slashed = <<<'SCRIPT'
<script src=\"https://example.com\"></script>
SCRIPT;

	/**
	 * Sample user link element unslashed.
	 *
	 * @var string
	 */
	protected $link_element_unslashed = <<<'LINK'
<link rel="stylesheet" href="https://example.com">
LINK;

	/**
	 * Sample user link elementslashed.
	 *
	 * @var string
	 */
	protected $link_element_slashed = <<<'LINK'
<link rel=\"stylesheet\" href=\"https://example.com\">
LINK;
	// phpcs:enable WordPress.WP.EnqueuedResources.NonEnqueuedScript

	/**
	 * Sets up the fixture, for example, open a network connection.
	 *
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		parent::setUp();
		new Genesis_Admin_Settings(); // Ensures save() function is used when updating settings.
	}

	/**
	 * Test sitewide scripts preserve regular expressions.
	 */
	public function test_sitewide_scripts_preserve_regular_expressions() {
		genesis_update_settings(
			[
				'header_scripts' => $this->script,
				'footer_scripts' => $this->script,
			]
		);

		$this->assertEquals( $this->script, genesis_get_option( 'header_scripts', GENESIS_SETTINGS_FIELD, false ) );
		$this->assertEquals( $this->script, genesis_get_option( 'footer_scripts', GENESIS_SETTINGS_FIELD, false ) );
	}

	/**
	 * Test sitewide styles are preserved.
	 */
	public function test_sitewide_styles_are_preserved() {
		genesis_update_settings(
			[
				'header_scripts' => $this->styles,
				'footer_scripts' => 'unset',
			]
		);

		$this->assertEquals( $this->styles, genesis_get_option( 'header_scripts', GENESIS_SETTINGS_FIELD, false ) );
	}

	/**
	 * Test sitewide meta tags are preserved.
	 */
	public function test_sitewide_meta_is_preserved() {
		genesis_update_settings(
			[
				'header_scripts' => $this->meta,
				'footer_scripts' => 'unset',
			]
		);

		$this->assertEquals( $this->meta, genesis_get_option( 'header_scripts', GENESIS_SETTINGS_FIELD, false ) );
	}

	/**
	 * Test sitewide script elements stay unslashed.
	 */
	public function test_sitewide_script_elements_stay_unslashed() {
		genesis_update_settings(
			[
				'header_scripts' => $this->script_element_unslashed,
				'footer_scripts' => $this->script_element_unslashed,
			]
		);

		$this->assertEquals( $this->script_element_unslashed, genesis_get_option( 'header_scripts', GENESIS_SETTINGS_FIELD, false ) );
		$this->assertEquals( $this->script_element_unslashed, genesis_get_option( 'footer_scripts', GENESIS_SETTINGS_FIELD, false ) );
	}

	/**
	 * Test sitewide script elements stay slashed.
	 */
	public function test_sitewide_script_elements_stay_slashed() {
		genesis_update_settings(
			[
				'header_scripts' => $this->script_element_slashed,
				'footer_scripts' => $this->script_element_slashed,
			]
		);

		$this->assertEquals( $this->script_element_slashed, genesis_get_option( 'header_scripts', GENESIS_SETTINGS_FIELD, false ) );
		$this->assertEquals( $this->script_element_slashed, genesis_get_option( 'footer_scripts', GENESIS_SETTINGS_FIELD, false ) );
	}

	/**
	 * Test sitewide link elements stay unslashed.
	 */
	public function test_sitewide_link_elements_stay_unslashed() {
		genesis_update_settings(
			[
				'header_scripts' => $this->link_element_unslashed,
				'footer_scripts' => $this->link_element_unslashed,
			]
		);

		$this->assertEquals( $this->link_element_unslashed, genesis_get_option( 'header_scripts', GENESIS_SETTINGS_FIELD, false ) );
		$this->assertEquals( $this->link_element_unslashed, genesis_get_option( 'footer_scripts', GENESIS_SETTINGS_FIELD, false ) );
	}


	/**
	 * Test sitewide link elements stay slashed.
	 */
	public function test_sitewide_link_elements_stay_slashed() {
		genesis_update_settings(
			[
				'header_scripts' => $this->link_element_slashed,
				'footer_scripts' => $this->link_element_slashed,
			]
		);

		$this->assertEquals( $this->link_element_slashed, genesis_get_option( 'header_scripts', GENESIS_SETTINGS_FIELD, false ) );
		$this->assertEquals( $this->link_element_slashed, genesis_get_option( 'footer_scripts', GENESIS_SETTINGS_FIELD, false ) );
	}

}
