<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Studiopress\Genesis
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

use Brain\Monkey;
use Brain\Monkey\Functions;

genesis_tests_bootstrap_unit_integration();

/**
 * Setup non-WordPress environment for unit testing Genesis.
 *
 * @since 2.6.0
 */
function genesis_tests_bootstrap_unit_integration() {
	define( 'GENESIS_THEME_DIR', dirname( dirname( __DIR__ ) ) );
	define( 'GENESIS_JS_URL', 'https://example.com/wp-content/themes/genesis/js' );

	// Load Brain Monkey, etc.
	require GENESIS_THEME_DIR . '/vendor/autoload.php';

	// Define a WP class that Genesis classes extend.
	if ( ! class_exists( 'WP_Widget' ) ) {
		/**
		 * Fake WP_Widget class for now.
		 */
		class WP_Widget {} // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedClassFound
	}

	// Define some WP functions with Brain Monkey.
	Monkey\setUp();
	Functions\when( 'trailingslashit' )->alias(
		static function ( $string ) {
				return rtrim( $string, '/\\' ) . '/';
		}
	);
	Functions\when( 'require_if_theme_supports' )->alias(
		static function ( $feature, $include ) {
				require $include;
		}
	);
	Functions\stubs(
		[
			'__',
			'_n',
			'_x',
			'_nx',
			'esc_html__',
			'esc_html_x',
			'esc_attr__',
			'esc_attr_x',
		]
	);
	Functions\when( 'add_shortcode' )->justReturn();
	Functions\when( 'do_shortcode' )->justReturn();
	Functions\when( 'wpautop' )->justReturn();
	Functions\when( 'is_admin' )->justReturn( true );
	Functions\when( 'is_customize_preview' )->justReturn( true );
	Functions\when( 'get_template_directory' )->justReturn( GENESIS_THEME_DIR );

	// Define key constants.
	$GLOBALS['wp_version'] = '999'; // phpcs:ignore WordPress.WP.GlobalVariablesOverride.Prohibited
	define( 'PARENT_DIR', GENESIS_THEME_DIR ); //phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedConstantFound
	define( 'PARENT_THEME_VERSION', '9999' );  //phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedConstantFound
	define( 'PARENT_DB_VERSION', '9999' );     //phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedConstantFound
	define( 'GENESIS_CONFIG_DIR', GENESIS_THEME_DIR . '/config/' );
	define( 'GENESIS_SETTINGS_FIELD', 'foo' );
	define( 'GENESIS_SEO_SETTINGS_FIELD', 'bar' );

	// Require a Genesis file, and get Genesis to to load the rest of itself.
	require GENESIS_THEME_DIR . '/lib/init.php';
	genesis_load_framework();
}
